Hospital/Hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('user.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Hospital/home/urls.py
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('',views.home_view,name='home_view')
]

Hospital/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/',views.login_view,name='login_view'),
    path('signup/',views.signup_view,name='signup_view'),
    path('logout/',views.logout_view,name='logout_view'),
    path('all/hospitals/',views.view_all_hospitals,name='view_all_hospitals'),
    path('profile/<user_id>/',views.profile_view,name='profile_view'),
    path('profile/update/<user_id>',views.update_profile_view,name='update_profile_view'),
    path('hospital/',views.investors_view,name='investors_view'),
    path('create/training/',views.add_training_view,name='add_training_view'),
    path('hospital/training/<hospital_id>/',views.all_training_view,name='all_training_view'),
]

Hospital/home/models.py
from django.db import models

# Create your models here.

Hospital/home/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest,HttpResponse
from django.contrib.auth.models import User
# Create your views here.


def home_view(request:HttpRequest):
    
    hospital = User.objects.filter(groups__name ='hospital')

    return render(request,'home/home.html',{'hospital':hospital})

Hospital/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% block title %} {% endblock %}
    <link rel="stylesheet" href="/static/css.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">


</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary mt-0">
        <div class="container-fluid primary-color-1 mt-0 pt-2">
          <a class="navbar-brand" href="">E-Elective</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:home_view' %}">Home</a>   
              </li>
              <li><a class="nav-link active" aria-current="page" href="{% url 'user:investors_view' %}">Hospitals</a></li>
              {% block hospital %}
              {% endblock %}
            </ul>
            <div class="d-flex gap-2">
              {% if request.user.is_authenticated %}
              <lu class="nav-item dropdown me-4">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Welcome, Mr.{{user.username}}
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item w-50" href="{% url 'user:profile_view' request.user.id %}">Profile</a></li>
                  <li><hr class="dropdown-divider"></li>
                  {% if  perms.startup.add_startup %}
                  <li><a class="dropdown-item" href="">Create Startup</a></li>
                  <li><a class="dropdown-item" href="">Startup</a></li>
                  {% endif %}
                  <li><a class="dropdown-item text-danger" href="{% url 'user:logout_view' %}">Logout</a></li>

                </ul>
              </lu>
              
              {% else %}
                <a class="nav-link" href="{% url 'user:login_view' %}">Login</a>
                <a class="nav-link" href="{% url 'user:signup_view' %}">SignUp</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

        {% block body %} 
        {% endblock %}
        <!-- Footer -->
        <div class="container pt-5 border-top " style="margin-top: 100px;">
            <footer class="py-5">
              <div class="row justify-content-between">
                <div class="col-6 col-md-2 mb-3">
                  <h5>Section</h5>
                  <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Service</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
                  </ul>
                </div>
                <div class="col-md-5 offset-md-1 mb-3 ">
                  <form>
                    <h5>Subscribe to our newsletter</h5>
                    <p>Monthly digest of what's new service and exciting from us.</p>
                    <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                      <label for="newsletter1" class="visually-hidden">Email address</label>
                      <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                      <button class="btn btn-primary" type="button">Subscribe</button>
                    </div>
                  </form>
                </div>
              </div>
          
              <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
                <p>© 2023 Horizontal Cloud, Inc. All rights reserved.</p>
                <ul class="list-unstyled d-flex">
                  <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
                  <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
                  <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
                </ul>
              </div>
            </footer>
        </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const observer = new IntersectionObserver(entries => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('animate__fadeInUp'); // Add the animation class for moving up
                }
            });
        }, { threshold: 0.5 }); // Adjust threshold as needed

        document.querySelectorAll('.wow').forEach(element => {
            observer.observe(element);
        });
    });
</script>
</body>
</html>

Hospital/home/templates/home/home.html
{% extends 'home/base.html' %}

{% block title %}
<title>Home</title>
{% endblock %}
{% if request.user.is_authenticated %}
  {% if user in hospital %}
    {% block hospital %}
      <li><a class="nav-link active" aria-current="page" href="{% url 'user:add_training_view' %}">Add Training</a></li>
    {% endblock %}
  {% endif %}
{% endif %}

{% block body %}
{% if massage %}
<div class="alert alert-danger" role="alert">
    {{massage}}
  </div>
  
{% endif %}
<div id="myCarousel" class="carousel slide mb-5 pointer-event " data-bs-ride="carousel">

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://www.snapcomms.com/hs-fs/hubfs/blog-images/healthcare-technology.jpg?width=1600&height=830&name=healthcare-technology.jpg" width="100%" height="100%" alt="">
        <div class="container ">
        <div class="carousel-caption text-start text-white">
          <h1>E-Elective</h1>
          <p>This is your guide for a better and good chances for your elective</p>
          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container marketing ">

  <!-- Three columns of text below the carousel -->
  <div class="row d-flex justify-content-center text-center">
    <h2 class="mb-4"> Students advantages </h2>
    <div class="col-lg-4 ">
      <img src="https://www.shutterstock.com/image-vector/hands-holding-smartphone-video-call-260nw-1831803718.jpg" class="bd-placeholder-img rounded-circle" width="140" height="140">

      <h2 class="fw-normal">Easy and simple</h2>
      
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img src="https://img.freepik.com/premium-vector/banking-service-online-get-credit-fast-easy-get-loan-via-smart-phone-application-flat-vector-modern-illustration_566886-10642.jpg" class="bd-placeholder-img rounded-circle" width="140" height="140">
      <h2 class="fw-normal">Provision of comprehensive information</h2>

    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img src="https://img.freepik.com/premium-vector/online-business-communication-remote-work-process-concept-boss-manager-giving-tasks-feedback-about-project-employee-distant-workflow-flat-vector-illustration-isolated-white-background_198278-19891.jpg" class="bd-placeholder-img rounded-circle" width="140" height="140">
      <h2 class="fw-normal">Fast and direct communication</h2>
      
    </div><!-- /.col-lg-4 -->
    <p><a class="btn btn-secondary" href="">Join Us »</a></p>
  </div><!-- /.row -->


  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <!-- Three columns of text below the carousel -->
  <div class="row d-flex justify-content-center text-center">
    <h2 class="mb-4"> Hospital advantages </h2>
    <div class="col-lg-4">
      <img src="https://static.vecteezy.com/system/resources/thumbnails/014/276/860/small_2x/search-for-right-direction-business-opportunity-or-success-way-make-decision-or-career-path-vision-to-see-future-concept-flat-modern-illustration-vector.jpg" class="bd-placeholder-img rounded-circle" width="140" height="140">
      <h2 class="fw-normal">Developing opportunities</h2>
      
      
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img src="https://unblast.com/wp-content/uploads/2020/03/Marketing-Campaign-Vector-Illustration-1.jpg" class="bd-placeholder-img rounded-circle" width="140" height="140">
      <h2 class="fw-normal">Way of advertisement</h2>
      
      
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img src="https://media.istockphoto.com/id/1342829273/vector/medical-tutor-with-students-semi-flat-color-vector-characters.jpg?s=612x612&w=0&k=20&c=nODTwfVSXOIszrnfp1L06mkulVgMrLWZSd6xNrdu2OA=" class="bd-placeholder-img rounded-circle" width="140" height="140">
      <h2 class="fw-normal">Improving training quality</h2>
      
      
    </div><!-- /.col-lg-4 -->
    <p><a class="btn btn-secondary" href="">Register now »</a></p>
  </div><!-- /.row -->




</div>

{% endblock %}