Hospital/Hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('user.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Hospital/home/urls.py
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('',views.home_view,name='home_view')
]

Hospital/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/',views.login_view,name='login_view'),
    path('signup/',views.signup_view,name='signup_view'),
    path('logout/',views.logout_view,name='logout_view'),
    path('all/hospitals/',views.view_all_hospitals,name='view_all_hospitals'),
    path('profile/<user_id>/',views.profile_view,name='profile_view'),
    path('profile/update/<user_id>',views.update_profile_view,name='update_profile_view'),
    path('hospital/',views.investors_view,name='investors_view'),
    path('create/training/',views.add_training_view,name='add_training_view'),
    path('hospital/training/<hospital_id>/',views.all_training_view,name='all_training_view'),
]

Hospital/user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class StudentProfile(models.Model):
    years_of_studies = models.TextChoices('years_of_studies',['3','4','5'])

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    major = models.CharField(max_length=255)
    university_name = models.TextField()
    linkedIn = models.URLField()
    x_link = models.URLField()
    year_of_study = models.CharField(max_length=255,choices=years_of_studies.choices)
    email = models.EmailField()
    cv = models.FileField()
    trascript = models.FileField()
    medical_health = models.FileField()
    bio = models.TextField()

    def __str__(self) -> str:
        return self.user.first_name
    

class Hospital(models.Model):
    students = models.TextChoices('students',['1','2','3','4','5','6','7','8','9','10'])
    deparments = models.TextChoices('deparments',['Surgery','Internal Medicine','Emergency','Orthopedic surgery','Ophthalmology'])

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    depatrtment = models.CharField(max_length=1024)
    training_period = models.TextField()
    number_of_student_need = models.CharField(max_length=1024,choices=students.choices)
    for_contact_number = models.TextField()
    for_contact_email = models.EmailField()
    image = models.ImageField(upload_to='images/')
    def __str__(self) -> str:
        return self.depatrtment

Hospital/user/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest,HttpResponse
from django.contrib.auth.models import User,Group
from django.contrib.auth import login, logout, authenticate
from .models import StudentProfile,Hospital
# Create your views here.


def login_view(request:HttpRequest):
    massage = ''
    if request.method == 'POST':
        try:
            user = authenticate(request, username=request.POST['username'],password=request.POST['password'])

            if user:
                login(request,user)
                return redirect('home:home_view')
            
        except Exception as e:
            massage = f'this error by {e}'
            return massage

    return render(request,'user/login.html',{'massage':massage})



def signup_view(request:HttpRequest):
    massage = ''
    if request.method == 'POST':
        try:

            new_user = User.objects.create_user(username=request.POST['username'],email=request.POST['email'],password=request.POST['password'])
            new_user.save()
            user_field = request.POST['selected_option']

            if user_field == 'student':
                if not new_user.groups.filter(name='student').exists():
                    group = Group.objects.get(name="student")
                    new_user.groups.add(group)

            elif user_field == 'hospital':
                if not new_user.groups.filter(name='hospital').exists():
                    group = Group.objects.get(name="hospital")
                    new_user.groups.add(group)
            
            new_user = authenticate(request, username=request.POST['username'],password=request.POST['password'])

            if new_user:
                login(request,new_user)
            
            if user_field == 'student':

                return redirect('user:profile_view',user_id=request.user.id)
            else:
                return redirect('home:home_view')
        
        except Exception as e:
            massage = f'this is th eroor'
            return massage
    
    return render(request,'user/signup.html',{'massage':massage})

def view_all_hospitals(request:HttpRequest):

    hospital = User.objects.filter(groups__name ='hospital')

    return redirect('home:home_view')

def logout_view(request:HttpRequest):

    if request.user.is_authenticated:

        logout(request)

        return redirect('user:login_view')
    
def profile_view(request:HttpRequest,user_id):
        
    msg = None
    user = User.objects.get(id=user_id)
    
    student = User.objects.filter(groups__name ='student')       

    if request.user in student:
        try:
            profile = request.user.StudentProfile
        except Exception:
            msg = 'Please update your profile'


    return render(request,'user/profile.html',{'user':user,'student':student,'massage':msg})


def update_profile_view(request:HttpRequest,user_id):

    user = User.objects.get(id=request.user.id)
    years = StudentProfile(user=user)
    if request.user.is_authenticated:
            if request.method == 'POST':

                user.first_name = request.POST['first_name']
                user.last_name =  request.POST['last_name']
                user.email = request.POST['email']

                user.save()

                try:
                    manager_profile=user.StudentProfile

                except Exception as e:
                        
                    manager_profile = StudentProfile(user=user)

                manager_profile.phone_number = request.POST['phone_number']
                manager_profile.major = request.POST['major']
                manager_profile.university_name = request.POST['university_name']
                manager_profile.x_link = request.POST['x_link']
                manager_profile.year_of_study = request.POST['year_of_study']
                manager_profile.cv = request.FILES['cv']
                manager_profile.linkedIn = request.POST['linkedIn']
                manager_profile.trascript = request.FILES['trascript']
                manager_profile.medical_health = request.FILES['medical_health']
                manager_profile.bio = request.POST['bio']                         
                                                            
                if 'manager_avatar' in request.FILES:

                        manager_profile.manager_avatar = request.FILES['manager_avatar']

                manager_profile.save()

                return redirect('user:profile_view',request.user.id)
    
    context = {
        'user':user,
        'years_of_studies':years.years_of_studies
    }                        
    return render(request,'user/update_profile.html',context)

def investors_view(request:HttpRequest):

    investors = User.objects.filter(groups__name ='hospital')

    return render(request,'user/investors.html',{'investors':investors})

def add_training_view(request:HttpRequest):

    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        new_training = Hospital(user=user,depatrtment=request.POST['depatrtment'],training_period=request.POST['training_period'],number_of_student_need=request.POST['number_of_student_need'],for_contact_number=request.POST['for_contact_number'],for_contact_email=request.POST['for_contact_email'],image=request.FILES['image'])
        new_training.save()
        return redirect('home:home_view')
    
    return render(request,'user/create_training.html',{'department':Hospital.deparments,'students':Hospital.students})

def all_training_view(request:HttpRequest,hospital_id):
    training = Hospital.objects.filter(user=hospital_id)

    return render(request,'user/hopsital_training.html',{'trainings':training})

Hospital/user/templates/user/create_training.html
{% extends 'home/base.html' %}
{% block title %} <title>create startup</title>{% endblock %}


{% block body %}
<section class="container primary-color-1 border rounded mt-5">
    <div class="container ms-0 p-2">
        <form class="row" action="{% url 'user:add_training_view' %}" method="POST" enctype="multipart/form-data">
            {% if massage %}
            <div class="alert alert-danger" role="alert">
                {{massage}}
            </div>
            {% endif %}

            {% csrf_token %}
            <h1>Training Form</h1>
            <div class="col-md-6">
                <label class="from-label">Student Capacity:</label>
                    <select name="number_of_student_need" class="form-select" required>
                        <option selected>Select Years</option>
                        {% for key,value in students.choices %}
                            <option value="{{key}}">{{value}}</option>
                        {% endfor %}
                    </select>
            </div>
            <div class="col-md-6">
                <label class="from-label">Department:</label>
                <select name="depatrtment" class="form-select">
                    <option value="" selected>Select Sector</option>
                    {% for key,value in department.choices %}
                    <option value="{{key}}">{{value}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-md-4">
                <label class="from-label">Department Number:</label>
                <div class="input-group mb-3">
                    <span class="input-group-text">+966</span>
                    <input type="number" class="form-control" placeholder="Number" name="for_contact_number">
                </div>
            </div>

            <div class="col-md-4">
                <label class="from-label">Department Email:</label>
                <input type="email" name="for_contact_email" class="form-control">
            </div>
            <div class="col-md-4">
                <label class="from-label">Training Period:</label>
                <input type="text" name="training_period" class="form-control">
            </div>
            <div class="col-md-12">
                <label for="trascript">Avatar:</label>
                <input type="file" id="trascript" name="image" value="{{user.studentprofile.trascript}}" class="form-control" required>
            </div>

            <div class="col-12 d-flex justify-content-center">
                <input type="submit" class="btn btn-primary mt-3 col-4">
            </div>
        </form>
    </div>
</section>
{% endblock %}

Hospital/user/templates/user/hopsital_training.html
{% extends 'home/base.html' %}

{% block title %}
<title> Hospital Training</title>
{% endblock %}

{% block body %}


<div class="container">
    
      <div class="row ">
        <h1>Hospital Training</h1>
    {% for training in trainings %}
    <div class="col mb-3">
      <div class="card shadow" style="width: 19rem; height: auto;">
        <div class="d-flex justify-content-center">
          <img src="{{ training.image.url }}" class="img-fluid rounded-pill img" alt="training avatar" style="width: 100px; height: 100px;">
        </div>
        <div class="card-body text-center">
          <h5 class="card-title ">{{training.user.username}}</h5>
          <div class="align-items-end p-0 m-0">
            <small class="text-body-secondary  ">Training Period</small>
            <h3> {{training.training_period}} </h3>

            <div class="progress" role="progressbar" aria-label="Info example" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
              <div class="progress-bar bg-info text-dark " style="width: 0%">0%</div>
            </div>
            <small class="text-body-secondary ">{{training.depatrtment}}</small>
        </div>
          <div class=" mt-3">
            <a href="" class="btn btn-outline-info ">More details</a>

          </div>
        </div>

        <div class="card-footer text-body-secondary d-flex justify-content-between ">
          <div>
            <i class="bi bi-person text-primary"></i><i>{{training.number_of_student_need}}</i>
          </div>
          <div>
            <i class="bi bi-archive text-warning"></i> <i>{{training.for_contact_email}}</i>

          </div>
          
        </div>
      </div>
    
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

Hospital/user/templates/user/investors.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %}<title>Investors</title>{% endblock %}

{% block body %}

<section>
    <div class="container mt-5">
        <div class="row justify-content-center">
            {% for investor in investors %}
            <div class="col-xl-8 mb-4 mb-4 wow animate__animated" data-wow-offset="150">
                <div class="card shadow-lg bg-light">
                    <div class="card-body pb-0">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <div class="text-center border-end">
                                    <h4 class="text-primary font-size-20 mt-3 mb-2"><a class="text-decoration-none" href="{% url 'user:all_training_view' investor.id %}">{{ investor.username }}</a></h4>
                                </div>
                            </div><!-- end col -->
                            <div class="col-md-6">
                                <div class="ms-3">
                                    <div class="row my-4">
                                        <div class="col-md-12">
                                            <div>
                                                <div class="mb-2">
                                                    <i class="bi bi-envelope me-2"></i>
                                                    <a href="mailto:{{investor.email}}" class="text-muted">{{investor.email}}</a>
                                                </div>
                                            </div>
                                        </div><!-- end col -->
                                    </div><!-- end row -->
                                </div>
                            </div><!-- end col -->
                        </div><!-- end row -->
                    </div><!-- end card body -->
                </div><!-- end card -->
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

Hospital/user/templates/user/login.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %}
    <title>Login</title>
{% endblock %}

{% block body %}

<section class="container primary-color-1 border rounded mt-5 shadow-lg">
    <div class="container">
        <div class="row  justify-content-center align-items-center">
            <h2 class="text-center mt-3 mb-3" >Log In</h2>
            <div class="col-md-6">
                {% if massage %}
                    <div class="alert alert-danger" role="alert">
                        {{ massage }}
                    </div>
                {% endif %}

                <form class="form-control mb-3" action="{% url 'user:login_view' %}" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label for="username" class="form-label">User Name</label>
                      <div class="input-group">
                          <span class="input-group-text"><i class="fas fa-user fa-lg fa-fw"></i></span>
                          <input type="text" class="form-control " id="username" required name="username">

                      </div>
                  </div>

                    <div class="mb-3">
                      <label for="password" class="form-label">Password</label>
                      <div class="input-group">
                          <span class="input-group-text"><i class="fas fa-lock fa-lg fa-fw"></i></span>
                          <input type="password"  class="form-control" id="password" required name="password">

                      </div>
                  </div>

                    <div class="mb-3 text-center">
                        <button type="submit" class="btn btn-primary">LogIn</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

Hospital/user/templates/user/profile.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %} <title>Profile</title>{% endblock %}

{% block body %}

<section class="vh-100">
{% if user in student %}
<div class="container mt-5">
    <div class="row justify-content-center">
        {% if request.user.id == user.id %}
        {% if massage %}
        <div class="alert alert-danger" role="alert">
            {{ massage }}
        </div>
        {% endif %}
        {% endif %}
        <div class="col-xl-12 mb-4">
            <div class="card shadow-lg ">
                <div class="card-body pb-0">
                    <div class="row align-items-center">
                        <div class="col-md-3">
                            <div class="text-center border-end">
                                <img src="{{ user.studentprofile.url }}" class="img-fluid avatar-xxl rounded" alt="">
                                <h4 class="text-primary font-size-20 mt-3 mb-2">{{ user.first_name }} {{ user.last_name }}</h4>
                                <h5 class="text-muted font-size-13 mb-0">{{ user.studentprofile.user }}</h5>
                            </div>
                        </div><!-- end col -->
                        <div class="col-md-9">
                            <div class="ms-3">
                                <div>
                                    <h4 class="card-title mb-2">Profile Student</h4>
                                    <p><strong>Major:</strong> {{ user.studentprofile.major }}</p>
                                    <p><strong>University:</strong> {{ user.studentprofile.university_name }}</p>
 
                                </div>
                                <div class="row my-4">
                                    <div class="col-md-12">
                                        <div>
                                            <div class="mb-2">
                                                <i class="bi bi-envelope me-2"></i>
                                                <a href="mailto:{{user.email}}" class="text-muted">{{user.email}}</a>
                                              </div>
                                              
                                              <div>
                                                <i class="bi bi-phone me-2"></i>
                                                <a href="tel:{{ user.studentprofile.phone_number }}" class="text-muted">{{ user.studentprofile.phone_number }}</a>
                                              </div>
                                        </div>
                                    </div><!-- end col -->
                                </div><!-- end row -->
                             
                                <ul class="nav nav-tabs nav-tabs-custom border-bottom-0 mt-3 nav-justfied" role="tablist">
                                    <li class="nav-item" role="presentation">

                                        <a class="nav-link px-4" href="{{ user.studentprofile.linkedIn }}" target="__blank">
                                            <i class="bi bi-linkedin"></i> LinkedIn
                                        </a>
                                    </li><!-- end li -->
                                    <li class="nav-item" role="presentation">
                                        <a class="nav-link px-4 "  href="{{ user.studentprofile.x_link }}" target="__blank">
                                            <i class="bi bi-twitter-x"></i>
                                        </a>
                                    </li><!-- end li -->
                                    <li class="nav-item" role="presentation">
                                        {% if request.user.id == user.id %}
                                        <a class="btn btn-primary" href="{% url 'user:update_profile_view' request.user.id %}">Update Profile</a>
                                        {% endif %}
                                    </li><!-- end li -->

                                </ul><!-- end ul -->
                            </div>
                        </div><!-- end col -->
                    </div><!-- end row -->
                </div><!-- end card body -->
            </div><!-- end card -->
           </div>
    </div> 
</div>
{% endif %}

</section>

{% endblock %}

Hospital/user/templates/user/signup.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %} <title>Logup</title>{% endblock %}



{% block body %}




<section  class="container primary-color-1 border rounded mt-5 shadow-lg" >
  <div class="container h-100">
      <div class="row justify-content-center align-items-center">
        <h2 class="text-center mb-3 mt-3" >Join us</h2>
          <div class="col-md-6">
              {% if massage %}
              <div class="alert alert-danger" role="alert">
                  {{ massage }}
              </div>
              {% endif %}
              <form class="form-control mb-3"  action="{% url 'user:signup_view' %}" method="POST">
                  {% csrf_token %}

                  <div class="mb-3">
                      <label for="username" class="form-label">User Name</label>
                      <div class="input-group">
                          <span class="input-group-text"><i class="fas fa-user fa-lg fa-fw"></i></span>
                          <input type="text" class="form-control" id="username" required name="username">

                      </div>
                  </div>

                  <div class="mb-3">
                      <label for="email" class="form-label">Email</label>
                      <div class="input-group">
                          <span class="input-group-text"><i class="fas fa-envelope fa-lg fa-fw"></i></span>
                          <input type="email" class="form-control" id="email" required name="email">

                      </div>
                  </div>

                  <div class="mb-3">
                      <label for="password" class="form-label">Password</label>
                      <div class="input-group">
                          <span class="input-group-text"><i class="fas fa-lock fa-lg fa-fw"></i></span>
                          <input type="password" minlength="8" class="form-control" id="password" required name="password">

                      </div>
                  </div>

                  <div class="mb-3">
                      <label for="dropdown" class="form-label">Choose Your Field</label>
                      <select class="form-select" id="dropdown" name="selected_option" required>
                          <option value="student">Student</option>
                          <option value="hospital">Hospital</option>
                      </select>

                  </div>

                  <div class="mb-3 text-center">
                      <button type="submit" class="btn btn-primary">Create User</button>
                  </div>
              </form>
          </div>
      </div>
  </div>
</section>


{% endblock %}

Hospital/user/templates/user/update_profile.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %} <title>Update Profile</title> {% endblock %}




{% block body %}

<section class="container primary-color-1 border rounded mt-5 shadow-lg">   
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center ">
        <h1 class="text-center" >Update Profile</h1>
        <div class="col-6  ">
            
            <form class="form-control mb-3"  action="{% url 'user:update_profile_view' request.user.id %}"  method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <!-- Manager Profile Information -->
                

                <div class="row mb-3">

                    <div class="col-6">
                        <label for="first_name">First Name:</label>
                        <input type="text" id="first_name" name="first_name" value="{{user.first_name}}" class="form-control" required>
                    </div>

                    <div class="col-6">
                        <label for="last_name">Last Name</label>
                        <input type="text" id="last_name" name="last_name" value="{{user.last_name}}" class="form-control" required>
                    </div>

                </div>

                <div class="row mb-3">

                    <div class="col-6">
                        <label for="email">Email</label>
                        <input type="email" id="email" name="email" value="{{user.email}}" class="form-control" required>
                    </div>  
                    
                    <div class="col-6">
                        <label for="phone_number">Phone Number:</label>
                        <div class="input-group mb-3">
                            <span class="input-group-text">+966</span>
                            <input  type="text" id="phone_number" name="phone_number" value="{{user.studentprofile.phone_number}}" maxlength="10" class="form-control" required>
                            
                        </div>
                        
                    </div>

                </div>

                <div class="row mb-3">

                    <div class="col-6">
                        <label for="cv">Resume:</label>
                        <input type="file" id="cv" name="cv" value="{{user.studentprofile.cv}}" class="form-control" required>
                    </div>

                    <div class="col-6">
                        <label for="trascript">Acedemic Trascript:</label>
                        <input type="file" id="trascript" name="trascript" value="{{user.studentprofile.trascript}}" class="form-control" required>
                    </div>

                    <div class="col-6">
                        <label for="medical_health">Medical Health:</label>
                        <input type="file" id="medical_health" name="medical_health" value="{{user.studentprofile.medical_health}}" class="form-control" required>
                    </div>

                    <div class="col-6">
                        <label for="major">Major: </label> 
                        <input type="text" id="major" name="major" class="form-control">
                    </div>

                </div>

                <div class="row mb-3">
                    <div class="col-6">
                        <label class="from-label">Years Of Study:</label>
                        <select name="year_of_study" class="form-select" required>
                            <option selected>Select Years</option>
                            {% for key,value in years_of_studies.choices %}
                                <option value="{{key}}">{{value}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="col-6">
                        <label for="university_name">University Name:</label>
                        <input type="text" id="university_name" value="{{user.studentprofile.university_name}}" name="university_name" class="form-control" required>
                    </div>

                </div>

                <div class="row mb-3" >

                    <div class="col-6">
                        <label for="x_link">X Link:</label>
                        <input type="url" id="x_link" value="{{user.studentprofile.x_link}}" name="x_link" class="form-control" required>
                    </div>

                    <div class="col-6">
                        <label for="linkedIn">LinkedIn Profile:</label>
                        <input type="url" id="linkedIn" value="{{user.studentprofile.linkedIn}}" name="linkedIn" class="form-control" required>
                    </div>

                </div>
                
                <div class="row mb-3">
                    <div class="form-group">
                        <label for="bio">Bio:</label>
                        <textarea id="bio" name="bio" class="form-control" rows="4" required>{{user.studentprofile.bio   }}</textarea>
                    </div>
                    
                </div>         
                <div class="mb-3 text-center">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
</section>






{% endblock %}